spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
  cache:
    type: redis

server:
  error:
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

kumbu:
  jwt:
    secret: ${KUMBU_JWT_SECRET}
  cors:
    allowed-origin-patterns: ${KUMBU_CORS_ORIGIN_PATTERNS:}
  cache:
    redis-enabled: true

logging:
  level:
    com.kumbu: INFO
    org.springframework.security: WARN

management:
  endpoints:
    web:
      exposure:
        include: health

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
