spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kumbu_db
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    show-sql: false

logging:
  level:
    com.kumbu: DEBUG
